"""SAST Audit Markdown Report Generator component."""

import hashlib
import json
from datetime import datetime
from pathlib import Path
from typing import Any

from src.domain.cwe_owasp_mapper import CWEOWASPMapper
from src.infrastructure.version_loader import get_plugin_version

DEFAULT_TEMPLATE_PATH = (
    Path(__file__).parent.parent.parent / "templates" / "report_template.md"
)

DEFAULT_FALLBACK_TEMPLATE = """# 🛡️ SAST Security Audit Report

> [!IMPORTANT]
> **Audit Date:** {{DATE}}
> **Target Path:** `{{TARGET_PATH}}`
> **Total Vulnerabilities:** `{{TOTAL_COUNT}}`

---

## 📊 Executive Summary

| Severity | Count | Status |
|---|---|---|
| 🔴 **Critical** | `{{CRITICAL_COUNT}}` | {{CRITICAL_STATUS}} |
| 🟠 **High** | `{{HIGH_COUNT}}` | {{HIGH_STATUS}} |
| 🟡 **Medium** | `{{MEDIUM_COUNT}}` | {{MEDIUM_STATUS}} |
| 🔵 **Low** | `{{LOW_COUNT}}` | {{LOW_STATUS}} |

---

## 🔍 Detailed Findings

{{FINDINGS_TABLE}}

---

## 💡 Remediation & Security Action Items

{{REMEDIATION_SUMMARY}}

---
*Report automatically generated by Security SAST Guard Plugin.*
"""


def _count_severities(findings: list[dict[str, Any]]) -> dict[str, int]:
    counts = {"critical": 0, "high": 0, "medium": 0, "low": 0}
    for f in findings:
        sev = str(f.get("severity", "")).lower()
        if sev in counts:
            counts[sev] += 1
    return counts


def _build_findings_table(findings: list[dict[str, Any]]) -> str:
    if not findings:
        return "✅ **Clean. No vulnerabilities detected.**"

    lines = [
        "| Rule ID | File & Line | Severity | Code Snippet | Scope |",
        "|---|---|---|---|---|",
    ]
    for f in findings:
        snippet = str(f.get("line_content", "")).replace("|", "\\|")
        rule_id = f.get("rule_id", "UNKNOWN")
        location = f"{f.get('path', 'unknown')}:{f.get('line', 0)}"
        severity = f.get("severity", "Medium")
        scope = f.get("scope", "global")
        lines.append(
            f"| `{rule_id}` | `{location}` | **{severity}** | `{snippet}` | `{scope}` |"
        )
    return "\n".join(lines)


def _extract_remediation(finding: Any) -> tuple[str, str] | None:
    if isinstance(finding, dict):
        remediation = finding.get("remediation")
        if isinstance(remediation, dict):
            before = remediation.get("fix_before")
            after = remediation.get("fix_after")
            if before and after:
                return str(before), str(after)
        before = finding.get("fix_before")
        after = finding.get("fix_after")
        if before and after:
            return str(before), str(after)
    elif hasattr(finding, "remediation"):
        remediation = getattr(finding, "remediation", None)
        if isinstance(remediation, dict):
            before = remediation.get("fix_before")
            after = remediation.get("fix_after")
            if before and after:
                return str(before), str(after)
    return None


def _build_remediation_summary(findings: list[dict[str, Any]]) -> str:
    if not findings:
        return "No remediation required."

    rules: set[str] = set()
    for f in findings:
        rid = (
            f.get("rule_id", "UNKNOWN")
            if isinstance(f, dict)
            else getattr(f, "rule_id", "UNKNOWN")
        )
        rules.add(rid)

    lines = [
        (
            "1. **Review High-Risk Snippets:** Prioritize fixing Critical and High"
            " severity findings immediately."
        ),
        "2. **Rule Violations Detected:** "
        + ", ".join(f"`{r}`" for r in sorted(rules)),
        (
            "3. **OWASP Best Practice:** Sanitize user input, strip dangerous"
            " inline event handlers, and enforce strict parameter validation."
        ),
    ]

    remediation_blocks: list[str] = []
    seen_rules: set[str] = set()

    for f in findings:
        rule_id = (
            f.get("rule_id", "UNKNOWN")
            if isinstance(f, dict)
            else getattr(f, "rule_id", "UNKNOWN")
        )
        if rule_id in seen_rules:
            continue

        remed = _extract_remediation(f)
        if remed:
            seen_rules.add(rule_id)
            fix_before, fix_after = remed
            snippet_block = (
                f"### 🛠️ Remediation Snippet: `{rule_id}`\n\n"
                f"**❌ Vulnerable Code (Before):**\n"
                f"```\n{fix_before}\n```\n\n"
                f"**✅ Secure Defense (After):**\n"
                f"```\n{fix_after}\n```"
            )
            remediation_blocks.append(snippet_block)

    if remediation_blocks:
        lines.append("")
        lines.extend(remediation_blocks)

    return "\n".join(lines)


# pylint: disable=too-many-arguments,too-many-positional-arguments,too-many-locals
def _substitute_placeholders(
    template: str,
    target_path: str,
    findings: list[dict[str, Any]],
    counts: dict[str, int],
    metadata: dict[str, Any] | None = None,
    audit_level: str = "full",
    ai_analysis: str | None = None,
) -> str:
    meta = metadata or {}
    scanned_files = meta.get("scanned_files", "N/A")
    ignored_files = meta.get("ignored_files", "N/A")
    total_lines = meta.get("total_lines", "N/A")
    duration = meta.get("duration_seconds", "N/A")
    rules_applied = meta.get("rules_applied", "N/A")
    fp_filtered = meta.get("false_positives_filtered", 0)
    inc_mode = "ON (Git Diff)" if meta.get("incremental_mode") else "OFF (Full Walk)"

    metadata_block = f"""
## 🔍 Audit Metadata & Transparency
| Metric | Value |
|---|---|
| 📂 **Target Path** | `{target_path}` |
| 🛡️ **Active Audit Level** | `{str(audit_level).upper()}` |
| ⚡ **Scan Mode** | `{inc_mode}` |
| 📄 **Scanned Files** | `{scanned_files}` |
| 🚫 **Ignored Files** | `{ignored_files}` |
| 📝 **Lines Analyzed** | `{total_lines}` |
| 🤖 **AI False-Positives Filtered** | `{fp_filtered}` |
| ⚙️ **Rules Applied** | `{rules_applied}` |
| ⏱️ **Scan Duration** | `{duration}s` |
"""

    substitutions = {
        "{{DATE}}": datetime.now().strftime("%Y-%m-%d %H:%M:%S"),
        "{{TARGET_PATH}}": target_path,
        "{{TOTAL_COUNT}}": str(len(findings)),
        "{{CRITICAL_COUNT}}": str(counts["critical"]),
        "{{HIGH_COUNT}}": str(counts["high"]),
        "{{MEDIUM_COUNT}}": str(counts["medium"]),
        "{{LOW_COUNT}}": str(counts["low"]),
        "{{CRITICAL_STATUS}}": "⚠️ Action Required" if counts["critical"] > 0 else "OK",
        "{{HIGH_STATUS}}": "⚠️ Action Required" if counts["high"] > 0 else "OK",
        "{{MEDIUM_STATUS}}": "Review Recommended" if counts["medium"] > 0 else "OK",
        "{{LOW_STATUS}}": "Info" if counts["low"] > 0 else "OK",
        "{{FINDINGS_TABLE}}": _build_findings_table(findings),
        "{{REMEDIATION_SUMMARY}}": _build_remediation_summary(findings),
    }
    content = template
    for key, val in substitutions.items():
        content = content.replace(key, val)

    if "## 🔍 Detailed Findings" in content:
        if ai_analysis:
            ai_block = f"## 🤖 AI Security Analysis\n\n{ai_analysis}\n\n---\n\n"
        else:
            ai_block = ""
        content = content.replace(
            "## 🔍 Detailed Findings",
            f"{metadata_block}\n---\n\n{ai_block}## 🔍 Detailed Findings",
        )
    return content


# pylint: disable=too-many-arguments,too-many-positional-arguments,too-many-locals
def generate_markdown_report(
    findings: list[dict[str, Any]],
    output_dir: str = "reports",
    target_path: str = ".",
    template_path: str | Path | None = None,
    metadata: dict[str, Any] | None = None,
    audit_level: str = "full",
    ai_analysis: str | None = None,
) -> tuple[str, str]:
    """Generate Markdown report file for SAST findings using template."""
    counts = _count_severities(findings)

    meta = metadata or {}
    scanned_count = meta.get("scanned_files", 0)
    lines_count = meta.get("total_lines", 0)
    duration_val = meta.get("duration_seconds", 0)
    scanned_str = (
        f" [Scanned {scanned_count} files, {lines_count} lines in {duration_val}s]"
    )

    if not findings:
        summary = (
            f"SAST Audit completed.{scanned_str} Total: 0 findings "
            "(Critical: 0, High: 0, Medium: 0, Low: 0)."
        )
        if not ai_analysis:
            return "", summary

    target_dir = Path(output_dir)
    target_dir.mkdir(parents=True, exist_ok=True)

    timestamp = datetime.now().strftime("%Y%m%d_%H%M%S")
    report_file = target_dir / f"sast_audit_report_{timestamp}.md"

    tmpl_file = Path(template_path) if template_path else DEFAULT_TEMPLATE_PATH
    template_content = (
        tmpl_file.read_text(encoding="utf-8")
        if tmpl_file.exists()
        else DEFAULT_FALLBACK_TEMPLATE
    )

    report_content = _substitute_placeholders(
        template_content,
        target_path,
        findings,
        counts,
        metadata,
        audit_level,
        ai_analysis,
    )
    report_file.write_text(report_content, encoding="utf-8")

    file_uri = report_file.resolve().as_uri()
    try:
        rel_path = report_file.resolve().relative_to(Path.cwd()).as_posix()
    except ValueError:
        rel_path = report_file.name

    summary = (
        f"SAST Audit completed.{scanned_str} Total: {len(findings)} findings "
        f"(Critical: {counts['critical']}, High: {counts['high']}, "
        f"Medium: {counts['medium']}, Low: {counts['low']}).\n"
        f"Detailed report saved to: [{rel_path}]({file_uri})"
    )
    return str(report_file), summary


def generate_json_report(
    findings: list[dict[str, Any]],
    output_dir: str = "reports",
    target_path: str = ".",
    metadata: dict[str, Any] | None = None,
    audit_level: str = "full",
) -> tuple[str, str]:
    """Generate JSON report file for SAST findings."""
    target_dir = Path(output_dir)
    target_dir.mkdir(parents=True, exist_ok=True)

    timestamp = datetime.now().strftime("%Y%m%d_%H%M%S")
    report_file = target_dir / f"sast_audit_report_{timestamp}.json"
    counts = _count_severities(findings)

    data = {
        "timestamp": datetime.now().isoformat(),
        "target_path": target_path,
        "audit_level": audit_level,
        "summary": counts,
        "findings_count": len(findings),
        "metadata": metadata or {},
        "findings": findings,
    }

    report_file.write_text(json.dumps(data, indent=2), encoding="utf-8")
    file_uri = report_file.resolve().as_uri()
    try:
        rel_path = report_file.resolve().relative_to(Path.cwd()).as_posix()
    except ValueError:
        rel_path = report_file.name

    summary = (
        f"SAST Audit completed. Total: {len(findings)} findings.\n"
        f"JSON report saved to: [{rel_path}]({file_uri})"
    )
    return str(report_file), summary


def _map_severity_to_sarif_level(severity: str) -> str:
    sev = str(severity).lower()
    if sev in ("critical", "high"):
        return "error"
    if sev == "medium":
        return "warning"
    return "note"


def _extract_cwe_owasp_properties(
    rule_id: str, finding: dict[str, Any]
) -> tuple[dict[str, Any], str | None]:
    """Extract CWE and OWASP metadata properties and helpUri for a rule."""
    cwe_id = finding.get("cwe") or finding.get("cwe_id")
    owasp_cat = finding.get("owasp") or finding.get("owasp_category")

    mapper = CWEOWASPMapper()
    mapping = mapper.get_mapping(rule_id)

    final_cwe_id = str(cwe_id) if cwe_id else mapping.cwe_id
    final_cwe_name = str(finding.get("cwe_name") or mapping.cwe_name)
    final_owasp_cat = str(owasp_cat) if owasp_cat else mapping.owasp_category
    final_owasp_name = str(finding.get("owasp_name") or mapping.owasp_name)

    tags = ["security", final_cwe_id, final_owasp_cat]
    properties: dict[str, Any] = {
        "tags": tags,
        "cwe": [final_cwe_id],
        "cweName": final_cwe_name,
        "owasp": [final_owasp_cat],
        "owaspName": final_owasp_name,
        "precision": "high",
    }

    help_uri = None
    cwe_num = "".join(filter(str.isdigit, final_cwe_id))
    if cwe_num:
        help_uri = f"https://cwe.mitre.org/data/definitions/{cwe_num}.html"

    return properties, help_uri


def _extract_fingerprints(
    rule_id: str, file_path: str, line_num: int, finding: dict[str, Any]
) -> dict[str, str]:
    """Extract or compute partial fingerprints for SARIF finding."""
    fp_hash = None
    for key in ("fingerprint", "fingerprint_id", "hash"):
        if finding.get(key):
            fp_hash = str(finding[key])
            break

    if not fp_hash:
        line_content = str(finding.get("line_content", ""))
        raw = f"{rule_id}:{file_path}:{line_num}:{line_content}"
        fp_hash = hashlib.sha256(raw.encode("utf-8")).hexdigest()

    return {
        "primaryLocationLineHash": fp_hash,
        "semanticFingerprint/v1": fp_hash,
    }


def _extract_code_flows(finding: dict[str, Any]) -> list[dict[str, Any]] | None:
    """Extract codeFlows from evidence graph or trace steps for SARIF location trace."""
    raw_nodes: list[Any] = []
    ev_graph = finding.get("evidence_graph")
    if ev_graph is not None:
        if hasattr(ev_graph, "nodes"):
            raw_nodes = getattr(ev_graph, "nodes", [])
        elif isinstance(ev_graph, dict) and "nodes" in ev_graph:
            raw_nodes = ev_graph.get("nodes", [])

    if not raw_nodes:
        for key in ("trace_steps", "taint_trace", "code_flow", "dataflow", "locations"):
            if key in finding and isinstance(finding[key], list):
                raw_nodes = finding[key]
                break

    if not raw_nodes:
        return None

    locations: list[dict[str, Any]] = []
    for node in raw_nodes:
        if hasattr(node, "file_path"):
            f_path = getattr(node, "file_path", "")
            l_num = getattr(node, "line_number", 1)
            n_type = getattr(node, "node_type", "step")
            snippet = getattr(node, "code_snippet", "") or getattr(node, "symbol", "")
        elif isinstance(node, dict):
            f_path = str(
                node.get("file_path") or node.get("file") or node.get("path") or ""
            )
            l_num = int(node.get("line_number") or node.get("line") or 1)
            n_type = str(
                node.get("node_type")
                or node.get("step_type")
                or node.get("type")
                or "step"
            )
            snippet = str(
                node.get("code_snippet")
                or node.get("snippet")
                or node.get("symbol")
                or ""
            )
        else:
            continue

        loc_entry = {
            "location": {
                "physicalLocation": {
                    "artifactLocation": {"uri": f_path},
                    "region": {"startLine": max(1, l_num)},
                },
                "message": {"text": f"[{n_type}] {snippet}".strip()},
            }
        }
        locations.append(loc_entry)

    if not locations:
        return None

    return [{"threadFlows": [{"locations": locations}]}]


# pylint: disable=too-many-arguments,too-many-positional-arguments,too-many-locals
def generate_sarif_report(
    findings: list[dict[str, Any]],
    output_dir: str = "reports",
    target_path: str = ".",
    metadata: dict[str, Any] | None = None,
    audit_level: str = "full",
) -> tuple[str, str]:
    target_dir = Path(output_dir)
    target_dir.mkdir(parents=True, exist_ok=True)

    timestamp = datetime.now().strftime("%Y%m%d_%H%M%S")
    report_file = target_dir / f"sast_audit_report_{timestamp}.sarif"

    rules_map: dict[str, dict[str, Any]] = {}
    results: list[dict[str, Any]] = []

    for finding in findings:
        rule_id = finding.get("rule_id", "UNKNOWN")
        rule_name = finding.get("rule_name") or rule_id
        description = finding.get("description") or rule_name
        severity = finding.get("severity", "Medium")
        sarif_level = _map_severity_to_sarif_level(severity)

        if rule_id not in rules_map:
            props, help_uri = _extract_cwe_owasp_properties(rule_id, finding)
            rule_entry: dict[str, Any] = {
                "id": rule_id,
                "name": rule_name,
                "shortDescription": {"text": description},
                "defaultConfiguration": {"level": sarif_level},
                "properties": props,
            }
            if help_uri:
                rule_entry["helpUri"] = help_uri
            rules_map[rule_id] = rule_entry

        msg_text = description
        if finding.get("line_content"):
            msg_text += f": {finding['line_content']}"

        file_path = str(finding.get("path", target_path))
        line_num = max(1, int(finding.get("line", 1)))

        result_entry: dict[str, Any] = {
            "ruleId": rule_id,
            "level": sarif_level,
            "message": {"text": msg_text},
            "locations": [
                {
                    "physicalLocation": {
                        "artifactLocation": {"uri": file_path},
                        "region": {"startLine": line_num},
                    }
                }
            ],
            "partialFingerprints": _extract_fingerprints(
                rule_id, file_path, line_num, finding
            ),
        }

        code_flows = _extract_code_flows(finding)
        if code_flows:
            result_entry["codeFlows"] = code_flows

        results.append(result_entry)

    sarif_data = {
        "$schema": (
            "https://raw.githubusercontent.com/oasis-tcs/sarif-spec/master/"
            "Schemata/sarif-schema-2.1.0.json"
        ),
        "version": "2.1.0",
        "runs": [
            {
                "tool": {
                    "driver": {
                        "name": "Security SAST Guard",
                        "semanticVersion": get_plugin_version(),
                        "informationUri": (
                            "https://github.com/nguyenduydan/security-sast-guard-plugin"
                        ),
                        "rules": list(rules_map.values()),
                    }
                },
                "taxonomies": [
                    {
                        "name": "CWE",
                        "version": "4.13",
                        "organization": "MITRE",
                        "shortDescription": {"text": "Common Weakness Enumeration"},
                    },
                    {
                        "name": "OWASP Top 10",
                        "version": "2021",
                        "organization": "OWASP",
                        "shortDescription": {"text": "OWASP Top 10 2021 Categories"},
                    },
                ],
                "invocations": [
                    {
                        "executionSuccessful": True,
                        "properties": {
                            "auditLevel": audit_level,
                            "metadata": metadata or {},
                            "targetPath": target_path,
                        },
                    }
                ],
                "results": results,
            }
        ],
    }

    report_file.write_text(json.dumps(sarif_data, indent=2), encoding="utf-8")
    file_uri = report_file.resolve().as_uri()
    try:
        rel_path = report_file.resolve().relative_to(Path.cwd()).as_posix()
    except ValueError:
        rel_path = report_file.name

    summary = (
        f"SAST Audit completed. Total: {len(findings)} findings.\n"
        f"SARIF report saved to: [{rel_path}]({file_uri})"
    )
    return str(report_file), summary
