"""SAST Audit Markdown Report Generator component."""

from datetime import datetime
from pathlib import Path
from typing import Any

DEFAULT_TEMPLATE_PATH = (
    Path(__file__).parent.parent.parent / "templates" / "report_template.md"
)

DEFAULT_FALLBACK_TEMPLATE = """# 🛡️ SAST Security Audit Report

> [!IMPORTANT]
> **Audit Date:** {{DATE}}
> **Target Path:** `{{TARGET_PATH}}`
> **Total Vulnerabilities:** `{{TOTAL_COUNT}}`

---

## 📊 Executive Summary

| Severity | Count | Status |
|---|---|---|
| 🔴 **Critical** | `{{CRITICAL_COUNT}}` | {{CRITICAL_STATUS}} |
| 🟠 **High** | `{{HIGH_COUNT}}` | {{HIGH_STATUS}} |
| 🟡 **Medium** | `{{MEDIUM_COUNT}}` | {{MEDIUM_STATUS}} |
| 🔵 **Low** | `{{LOW_COUNT}}` | {{LOW_STATUS}} |

---

## 🔍 Detailed Findings

{{FINDINGS_TABLE}}

---

## 💡 Remediation & Security Action Items

{{REMEDIATION_SUMMARY}}

---
*Report automatically generated by Security SAST Guard Plugin.*
"""


def _count_severities(findings: list[dict[str, Any]]) -> dict[str, int]:
    counts = {"critical": 0, "high": 0, "medium": 0, "low": 0}
    for f in findings:
        sev = str(f.get("severity", "")).lower()
        if sev in counts:
            counts[sev] += 1
    return counts


def _build_findings_table(findings: list[dict[str, Any]]) -> str:
    if not findings:
        return "✅ **Clean. No vulnerabilities detected.**"

    lines = [
        "| Rule ID | File & Line | Severity | Code Snippet | Scope |",
        "|---|---|---|---|---|",
    ]
    for f in findings:
        snippet = str(f.get("line_content", "")).replace("|", "\\|")
        rule_id = f.get("rule_id", "UNKNOWN")
        location = f"{f.get('path', 'unknown')}:{f.get('line', 0)}"
        severity = f.get("severity", "Medium")
        scope = f.get("scope", "global")
        lines.append(
            f"| `{rule_id}` | `{location}` | **{severity}** | `{snippet}` | `{scope}` |"
        )
    return "\n".join(lines)


def _build_remediation_summary(findings: list[dict[str, Any]]) -> str:
    if not findings:
        return "No remediation required."

    rules = sorted({f.get("rule_id", "UNKNOWN") for f in findings})
    lines = [
        (
            "1. **Review High-Risk Snippets:** Prioritize fixing Critical and High"
            " severity findings immediately."
        ),
        "2. **Rule Violations Detected:** " + ", ".join(f"`{r}`" for r in rules),
        (
            "3. **OWASP Best Practice:** Sanitize user input, strip dangerous"
            " inline event handlers, and enforce strict parameter validation."
        ),
    ]
    return "\n".join(lines)


# pylint: disable=too-many-arguments,too-many-positional-arguments,too-many-locals
def _substitute_placeholders(
    template: str,
    target_path: str,
    findings: list[dict[str, Any]],
    counts: dict[str, int],
    metadata: dict[str, Any] | None = None,
    audit_level: str = "full",
) -> str:
    meta = metadata or {}
    scanned_files = meta.get("scanned_files", "N/A")
    ignored_files = meta.get("ignored_files", "N/A")
    total_lines = meta.get("total_lines", "N/A")
    duration = meta.get("duration_seconds", "N/A")
    rules_applied = meta.get("rules_applied", "N/A")
    fp_filtered = meta.get("false_positives_filtered", 0)
    inc_mode = "ON (Git Diff)" if meta.get("incremental_mode") else "OFF (Full Walk)"

    metadata_block = f"""
## 🔍 Audit Metadata & Transparency
| Metric | Value |
|---|---|
| 📂 **Target Path** | `{target_path}` |
| 🛡️ **Active Audit Level** | `{str(audit_level).upper()}` |
| ⚡ **Scan Mode** | `{inc_mode}` |
| 📄 **Scanned Files** | `{scanned_files}` |
| 🚫 **Ignored Files** | `{ignored_files}` |
| 📝 **Lines Analyzed** | `{total_lines}` |
| 🤖 **AI False-Positives Filtered** | `{fp_filtered}` |
| ⚙️ **Rules Applied** | `{rules_applied}` |
| ⏱️ **Scan Duration** | `{duration}s` |
"""

    substitutions = {
        "{{DATE}}": datetime.now().strftime("%Y-%m-%d %H:%M:%S"),
        "{{TARGET_PATH}}": target_path,
        "{{TOTAL_COUNT}}": str(len(findings)),
        "{{CRITICAL_COUNT}}": str(counts["critical"]),
        "{{HIGH_COUNT}}": str(counts["high"]),
        "{{MEDIUM_COUNT}}": str(counts["medium"]),
        "{{LOW_COUNT}}": str(counts["low"]),
        "{{CRITICAL_STATUS}}": "⚠️ Action Required" if counts["critical"] > 0 else "OK",
        "{{HIGH_STATUS}}": "⚠️ Action Required" if counts["high"] > 0 else "OK",
        "{{MEDIUM_STATUS}}": "Review Recommended" if counts["medium"] > 0 else "OK",
        "{{LOW_STATUS}}": "Info" if counts["low"] > 0 else "OK",
        "{{FINDINGS_TABLE}}": _build_findings_table(findings),
        "{{REMEDIATION_SUMMARY}}": _build_remediation_summary(findings),
    }
    content = template
    for key, val in substitutions.items():
        content = content.replace(key, val)

    if "## 🔍 Detailed Findings" in content:
        content = content.replace(
            "## 🔍 Detailed Findings",
            f"{metadata_block}\n---\n\n## 🔍 Detailed Findings",
        )
    return content


# pylint: disable=too-many-arguments,too-many-positional-arguments,too-many-locals
def generate_markdown_report(
    findings: list[dict[str, Any]],
    output_dir: str = "reports",
    target_path: str = ".",
    template_path: str | Path | None = None,
    metadata: dict[str, Any] | None = None,
    audit_level: str = "full",
) -> tuple[str, str]:
    """Generate Markdown report file for SAST findings using template."""
    target_dir = Path(output_dir)
    target_dir.mkdir(parents=True, exist_ok=True)

    timestamp = datetime.now().strftime("%Y%m%d_%H%M%S")
    report_file = target_dir / f"sast_audit_report_{timestamp}.md"
    counts = _count_severities(findings)

    tmpl_file = Path(template_path) if template_path else DEFAULT_TEMPLATE_PATH
    template_content = (
        tmpl_file.read_text(encoding="utf-8")
        if tmpl_file.exists()
        else DEFAULT_FALLBACK_TEMPLATE
    )

    report_content = _substitute_placeholders(
        template_content, target_path, findings, counts, metadata, audit_level
    )
    report_file.write_text(report_content, encoding="utf-8")

    file_uri = report_file.resolve().as_uri()
    meta = metadata or {}
    scanned_count = meta.get("scanned_files", 0)
    lines_count = meta.get("total_lines", 0)
    duration_val = meta.get("duration_seconds", 0)
    scanned_str = (
        f" [Scanned {scanned_count} files, {lines_count} lines in {duration_val}s]"
    )
    summary = (
        f"SAST Audit completed.{scanned_str} Total: {len(findings)} findings "
        f"(Critical: {counts['critical']}, High: {counts['high']}, "
        f"Medium: {counts['medium']}, Low: {counts['low']}).\n"
        f"Detailed report saved to: [{report_file.name}]({file_uri})"
    )
    return str(report_file), summary


def generate_json_report(
    findings: list[dict[str, Any]],
    output_dir: str = "reports",
    target_path: str = ".",
    metadata: dict[str, Any] | None = None,
    audit_level: str = "full",
) -> tuple[str, str]:
    """Generate JSON report file for SAST findings."""
    import json

    target_dir = Path(output_dir)
    target_dir.mkdir(parents=True, exist_ok=True)

    timestamp = datetime.now().strftime("%Y%m%d_%H%M%S")
    report_file = target_dir / f"sast_audit_report_{timestamp}.json"
    counts = _count_severities(findings)

    data = {
        "timestamp": datetime.now().isoformat(),
        "target_path": target_path,
        "audit_level": audit_level,
        "summary": counts,
        "findings_count": len(findings),
        "metadata": metadata or {},
        "findings": findings,
    }

    report_file.write_text(json.dumps(data, indent=2), encoding="utf-8")
    file_uri = report_file.resolve().as_uri()

    summary = (
        f"SAST Audit completed. Total: {len(findings)} findings.\n"
        f"JSON report saved to: [{report_file.name}]({file_uri})"
    )
    return str(report_file), summary
