"""SAST Audit Markdown Report Generator component."""

from datetime import datetime
from pathlib import Path
from typing import Any

DEFAULT_TEMPLATE_PATH = (
    Path(__file__).parent.parent.parent / "templates" / "report_template.md"
)

DEFAULT_FALLBACK_TEMPLATE = """# 🛡️ SAST Security Audit Report

> [!IMPORTANT]
> **Audit Date:** {{DATE}}  
> **Target Path:** `{{TARGET_PATH}}`  
> **Total Vulnerabilities:** `{{TOTAL_COUNT}}`  

---

## 📊 Executive Summary

| Severity | Count | Status |
|---|---|---|
| 🔴 **Critical** | `{{CRITICAL_COUNT}}` | {{CRITICAL_STATUS}} |
| 🟠 **High** | `{{HIGH_COUNT}}` | {{HIGH_STATUS}} |
| 🟡 **Medium** | `{{MEDIUM_COUNT}}` | {{MEDIUM_STATUS}} |
| 🔵 **Low** | `{{LOW_COUNT}}` | {{LOW_STATUS}} |

---

## 🔍 Detailed Findings

{{FINDINGS_TABLE}}

---

## 💡 Remediation & Security Action Items

{{REMEDIATION_SUMMARY}}

---
*Report automatically generated by Security SAST Guard Plugin.*
"""


def _count_severities(findings: list[dict[str, Any]]) -> dict[str, int]:
    counts = {"critical": 0, "high": 0, "medium": 0, "low": 0}
    for f in findings:
        sev = str(f.get("severity", "")).lower()
        if sev in counts:
            counts[sev] += 1
    return counts


def _build_findings_table(findings: list[dict[str, Any]]) -> str:
    if not findings:
        return "✅ **Clean. No vulnerabilities detected.**"

    lines = [
        "| Rule ID | File & Line | Severity | Code Snippet | Scope |",
        "|---|---|---|---|---|",
    ]
    for f in findings:
        snippet = str(f.get("line_content", "")).replace("|", "\\|")
        rule_id = f.get("rule_id", "UNKNOWN")
        location = f"{f.get('path', 'unknown')}:{f.get('line', 0)}"
        severity = f.get("severity", "Medium")
        scope = f.get("scope", "global")
        lines.append(
            f"| `{rule_id}` | `{location}` | **{severity}** | `{snippet}` | `{scope}` |"
        )
    return "\n".join(lines)


def _build_remediation_summary(findings: list[dict[str, Any]]) -> str:
    if not findings:
        return "No remediation required."

    rules = sorted({f.get("rule_id", "UNKNOWN") for f in findings})
    lines = [
        (
            "1. **Review High-Risk Snippets:** Prioritize fixing Critical and High"
            " severity findings immediately."
        ),
        "2. **Rule Violations Detected:** " + ", ".join(f"`{r}`" for r in rules),
        (
            "3. **OWASP Best Practice:** Sanitize user input, strip dangerous"
            " inline event handlers, and enforce strict parameter validation."
        ),
    ]
    return "\n".join(lines)


def generate_markdown_report(
    findings: list[dict[str, Any]],
    output_dir: str = "reports",
    target_path: str = ".",
    template_path: str | Path | None = None,
) -> tuple[str, str]:
    """Generate Markdown report file for SAST findings using template."""
    target_dir = Path(output_dir)
    target_dir.mkdir(parents=True, exist_ok=True)

    timestamp = datetime.now().strftime("%Y%m%d_%H%M%S")
    report_file = target_dir / f"sast_audit_report_{timestamp}.md"
    counts = _count_severities(findings)

    # Load template
    tmpl_file = Path(template_path) if template_path else DEFAULT_TEMPLATE_PATH
    if tmpl_file.exists():
        template_content = tmpl_file.read_text(encoding="utf-8")
    else:
        template_content = DEFAULT_FALLBACK_TEMPLATE

    crit_status = "⚠️ Action Required" if counts["critical"] > 0 else "OK"
    high_status = "⚠️ Action Required" if counts["high"] > 0 else "OK"
    med_status = "Review Recommended" if counts["medium"] > 0 else "OK"
    low_status = "Info" if counts["low"] > 0 else "OK"

    table_md = _build_findings_table(findings)
    remediation_md = _build_remediation_summary(findings)

    # Perform substitutions
    report_content = (
        template_content.replace(
            "{{DATE}}", datetime.now().strftime("%Y-%m-%d %H:%M:%S")
        )
        .replace("{{TARGET_PATH}}", target_path)
        .replace("{{TOTAL_COUNT}}", str(len(findings)))
        .replace("{{CRITICAL_COUNT}}", str(counts["critical"]))
        .replace("{{HIGH_COUNT}}", str(counts["high"]))
        .replace("{{MEDIUM_COUNT}}", str(counts["medium"]))
        .replace("{{LOW_COUNT}}", str(counts["low"]))
        .replace("{{CRITICAL_STATUS}}", crit_status)
        .replace("{{HIGH_STATUS}}", high_status)
        .replace("{{MEDIUM_STATUS}}", med_status)
        .replace("{{LOW_STATUS}}", low_status)
        .replace("{{FINDINGS_TABLE}}", table_md)
        .replace("{{REMEDIATION_SUMMARY}}", remediation_md)
    )

    report_file.write_text(report_content, encoding="utf-8")

    file_uri = report_file.resolve().as_uri()
    summary = (
        f"SAST Audit completed. Total: {len(findings)} findings "
        f"(Critical: {counts['critical']}, High: {counts['high']}, "
        f"Medium: {counts['medium']}, Low: {counts['low']}).\n"
        f"Detailed report saved to: [{report_file.name}]({file_uri})"
    )

    return str(report_file), summary
